#ifndef HSD_VERSION_H
#define HSD_VERSION_H

#define HSD_VERSION_MAJOR 1
#define HSD_VERSION_MINOR 17
#define HSD_VERSION_PATCH 0
#define HSD_VERSION_BUILD 0

#define HSD_VERSION_RC 1,17,0,0
#define HSD_VERSION_STR "1.17"
#define HSD_VERSION_WIN_STR "1.17.0.0"

#endif
